[package]
name = "tagma-raft"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true

[features]
serde = ["dep:serde"]
planted-bugs = []

[dependencies]
serde = { workspace = true, optional = true }

[lints]
workspace = true
